### ISSUE TITLE
Error raised when running multimix

### ISSUE THREAD

**Issue by camiloromers** [BDonnot/lightsim2grid#8]
## Environment
 - Grid2op version: `1.1.0`
 - System: `osx`

## Bug description
Cannot initialize multimix env. It raises an error with the following message
```
TypeError: can't pickle lightsim2grid_cpp.GridModel objects
```

## How to reproduce
```python
import grid2op
from lightsim2grid import LightSimBackend

env = grid2op.make('l2rpn_neurips_2020_track2', backend=LightSimBackend(), test=True)
```
## Current output

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/grid2op/MakeEnv/Make.py", line 264, in make
    return make_from_path_fn(dataset_path=ds_path, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/grid2op/MakeEnv/Make.py", line 172, in _aux_make_multimix
    return MultiMixEnvironment(dataset_path, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/grid2op/Environment/MultiMixEnv.py", line 75, in __init__
    tmp_env = copy.deepcopy(self.current_env)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle lightsim2grid_cpp.GridModel objects
```

**Comment by BDonnot** [comment]
This issue has been fixed in the latest version of grid2op :-)
